apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
  name: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    name: nginx
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nginx
        app: nginx
    spec:
      containers:
      - name: nginx
        image: gcr.io/static-nomad-155909/nginx:v9
        ports:
        - name: nginx
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
  labels:
    name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
        app: redis
    spec:
      containers:
      - name: redis
        image: gcr.io/static-nomad-155909/redis:v1
        ports:
        - name: redis
          containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: publisher
  name: publisher
spec:
  type: LoadBalancer
  ports:
    - port: 11111
      targetPort: 11111
  selector:
    name: publisher
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: publisher
  labels:
    name: publisher
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: publisher
        app: publisher
    spec:
      containers:
      - name: publisher
        image: gcr.io/static-nomad-155909/publisher:v2
        ports:
        - name: publisher
          containerPort: 11111
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: subscriber
  name: subscriber
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: subscriber
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: subscriber
  labels:
    name: subscriber
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: subscriber
        app: subscriber
    spec:
      containers:
      - name: subscriber
        image: gcr.io/static-nomad-155909/subscriber:v4
        ports:
        - name: subscriber
          containerPort: 3000
